### ISSUE TITLE
Provide access to raw redis client for advanced usage

### ISSUE THREAD

**Issue by cludden** [dial-once/node-cache-manager-redis#11]
would like to be able to access the underlying redis client to use some native functionality, but there is currently no way to access it

**Comment by jkernech** [comment]
Thanks for your contribution @cludden ! I'll check this out as soon as possible

**Comment by cludden** [comment]
Thanks @jkernech for the fast response! Any chance you could publish v0.2.0? We're hoping to use some of this functionality in production at my company in the very near future.

**Comment by jkernech** [comment]
@cludden, I will publish a new version by the end of the week. 

I'd like to cover 100% of the code before releasing the v0.2.0  (~94% atm) 

https://github.com/dial-once/node-cache-manager-redis/tree/feature/tests

**Comment by jkernech** [comment]
I didn't manage to get the code coverage to 100% (~95%) but as promised I have published the v0.2.0.

**Comment by cludden** [comment]
Thanks @jkernech! Let me know if you'd like help on completing coverage, would be more than happy to help out on such a noble goal!

**Comment by jkernech** [comment]
Thanks @cludden ! I need some help to reach this noble goal so you're welcome to help out :)

We need to find a way to test the `connect` callback when the redis client throws an error, I will create a dedicated issue but you can find more infos here : https://github.com/dial-once/node-cache-manager-redis/pull/14

**Comment by jkernech** [comment]
Here you go ; #16
