### ISSUE TITLE
Ability to override isCacheableValue using node-cache-manager options. 

### ISSUE THREAD

**Issue by 3choBoomer** [dial-once/node-cache-manager-redis#19]
I may have a unique use-case here, but I still think others might find this functionality useful.

I needed the ability to write to one redis server (a master), but read from a pool of redis servers that were load balanced behind an HAProxy (a master and all of its slaves). 

I first wanted to use HAProxy, but it doesn't support routing via TCP.

After trying a few major refactors of `node-cache-manager-redis`, I decided that a more simple solution could be found by following the patterns already in place in `node-cache-manager`.

I made changes to `node-cache-manager-redis` to allow the passing of a function or value to be used in place of the default `isCacheableValue` function.

Now I can use the `multiCache` functionality of `node-cache-manager` to read from the tiered caches defined in the constructor, but only write to one of them like so:

```
var cacheManager = require('cache-manager');
var redisStore = require('cache-manager-redis');

var neverCache = function() {
  return false;
};

var redisMasterCache = cacheManager.caching({
  store: redisStore,
  host: config.redis.cache.master.host,
  port: config.redis.cache.master.port,
  ttl: config.redis.cache.master.ttl || config.redis.cache.ttl || 600
});

var redisLoadCache = cacheManager.caching({
  store: redisStore,
  host: config.redis.cache.proxy.host,
  port: config.redis.cache.proxy.port,
  isCacheableValue: neverCache //never write to the load balancer
});

//This config will always try to read from the load balancer instance first, then the master.
//the config of redisLoadCache dictates that it will never be written to.
//redis master will get all writes, then those will propagate to all redis slaves, which will be available via redisLoadCache.
var multiCache = cacheManager.multiCaching([redisLoadCache, redisMasterCache]);
```

My rather simple changes and tests for the new functionality can be found in this PR:

https://github.com/dial-once/node-cache-manager-redis/pull/20

**Comment by jkernech** [comment]
Thanks @3choBoomer. Interesting case..
I'll check this out soon !

**Comment by 3choBoomer** [comment]
Is there anything I need to do to get a clean build? The errors being thrown seem like they are environmental, but I wanted to be sure.

**Comment by jkernech** [comment]
Thanks @3choBoomer. 
Your issue and PR really make sense and your implementation and use case are consistent with the https://github.com/BryanDonovan/node-cache-manager library. 

The issue you mentionned is related to the cyclomatic complexity: https://www.codacy.com/app/dialonce-jkernech/node-cache-manager-redis/pullRequest?prid=165333

**Comment by jkernech** [comment]
@3choBoomer I have integrated your feature and published a new version on npm: https://www.npmjs.com/package/cache-manager-redis

Hope this helps !
