### ISSUE TITLE
APPEND

### ISSUE THREAD

**Issue by fscardua** [dial-once/node-cache-manager-redis#21]
You will plan to implement the redis APPEND function?

**Comment by jkernech** [comment]
Thanks for the suggestion @fscardua 
I will take a look and of course if you have time to do a PR, it would be awesome ;-)

**Comment by cludden** [comment]
@fscardua, you can access all redis commands by accessing the underlying redis client using the #getClient() method:
```javascript
// lease a redis client from the connection pool
redisCache.store.getClient(function(err, redis) {
    // do something with the client
    redis.client.append(/* ...args */);
    // don't forget to return client to the pool when finished
    redis.done();
});
```
