### ISSUE TITLE
Version bump for npm?

### ISSUE THREAD

**Issue by kjs3** [dial-once/node-cache-manager-redis#35]
There's some good work on master (specifically, thank you for [this](https://github.com/dial-once/node-cache-manager-redis/pull/33))

How about a version bump for npm so you don't need to install from github?

**Comment by jkernech** [comment]
Thanks @kjs3 ! We planned to release and publish a new version in a few days :)

**Comment by jkernech** [comment]
Hey @kjs3 !! 
As promised, a new version (v0.2.3) have been published on npm !

https://www.npmjs.com/package/cache-manager-redis

Cheers
