### ISSUE TITLE
wrap with {ttl: 0} is caching forever

### ISSUE THREAD

**Issue by pasupulaphani** [dial-once/node-cache-manager-redis#36]
```redisCache.wrap("key", () => Promise.resolve("hit"), {ttl: 0});```

**Comment by mrister** [comment]
@pasupulaphani Would you mind giving us a code example here to check ?

**Comment by pasupulaphani** [comment]
@mrister Added sample code.

**Comment by mrister** [comment]
@pasupulaphani  tnx!

**Comment by PuKoren** [comment]
This is expected behaviour as having a ttl of 0 makes no sense (why would you store something that is to be deleted instantly?). So 0 was defined as 'infinite'

Can you describe what you are trying to achieve? Because I fail to see the benefits of using the cache module to not cache 😆

**Comment by pasupulaphani** [comment]
I wasn't deliberate in doing that. Found this when testing edge cases.

I wouldn't recommend making the assumption 0 as 'infinite'. Only suggesting. Feel free to close the issue if you feel this is not a biggy.

**Comment by PuKoren** [comment]
Thing is with redis TTL of -1 and -2 have a meaning: http://redis.io/commands/ttl, as well as positive integers.

About 0 = infinite, the mother module (node-cache-manager) works this ways on its memory cache, it makes sense to me to be consistent with it and use the same API.

Why do you recommend to avoid using ttl: 0 as an infinite ttl value?

**Comment by pasupulaphani** [comment]
Thank you for the explanation. I can see now why it is implemented this way.
