### ISSUE TITLE
Redis unavailable fallback.

### ISSUE THREAD

**Issue by raj-krrish** [dial-once/node-cache-manager-redis#37]
If redis goes down, function does not return and user request hangs up. Can not see any workaround in examples.

**Comment by mrister** [comment]
Hi @raj-krrish . Would you be kind and provide a code sample and a scenario helping us recreate this ?

**Comment by raj-krrish** [comment]
Thanks for quick response.
`redisCache.wrap(redisKey,
                        function(cacheCB){
                            audiencePoolWrapper(cacheCB)
                        },
                        function(err,response){
                            if(err){  // send resPayload  directly as response will not be available
                                sendErrResponse(req,res);
                                return;
                            }
                            // send response to user
                            res.json(response);
                        }
                    );`

It works perfectly if redis is up. But in case redis goes down,  then it keeps retrying to connect to redis and request hangs up. Do we have any options to configure max-attempts or timeout ?

**Comment by mrister** [comment]
Have you tried setting any Redis reconnect options like retry_strategy when creating redis store? https://github.com/NodeRedis/node_redis#options-object-properties

**Comment by raj-krrish** [comment]
Yes I tried that. This is my code to create client.
`var redisCache= cacheManager.caching({`
`    "store": redisStore,`
`    "host": config.redis.host,`
`    "port": config.redis.port,`
`    "db" : config.redis.db,
`    "ttl" : config.redis.ttl,`
`    "retry_strategy": function(options){`
`        if (options.error.code === 'ECONNREFUSED') {`
`            // End reconnecting on a specific error and flush all commands with a individual error`
`            return new Error('The server refused the connection');`
`        }`
`        if (options.total_retry_time > 3) {`
`            // End reconnecting after a specific timeout and flush all commands with a individual error`
`            return new Error('Retry time exhausted');`
`        }`
`        if (options.times_connected > 1) {`
 `           // End reconnecting with built in error`
`            return undefined;`
`        }`
`        // reconnect after`
`        return Math.max(options.attempt * 100, 3000);`
`    }`
`});`
But it is still behaving in the same way.

**Comment by raj-krrish** [comment]
I guess "retry_strategy" is being filtered by 
` copyAllowedKeys(SUPPORTED_REDIS_OPTIONS, redisOptions, {});`
in sol-redis-pool/index.js line 41.
as adding 
`self._redis_options.retry_strategy = redisOptions.retry_strategy;` 
after that is changing the behavior.

**Comment by mrister** [comment]
@raj-krrish  yes there is a PR for this https://github.com/joshuah/sol-redis-pool/pull/17, unfortunately not yet merged.

**Comment by joshuah** [comment]
I just published version 0.3.0 to add the `retry_strategy`. 
```js
retry_strategy: function (options) {
        if (options.times_connected > 10) {
            // Stop retrying afer 10 attempts.
            return undefined;
        }
        // Increase reconnect delay by 150ms.
        return options.attempt * 150;
    }
```

There are some breaking changes in this release, notes are in the README.md

**Comment by raj-krrish** [comment]
Thanks :)  @mrister @joshuah

**Comment by PuKoren** [comment]
As minimum version now is greater than 0.3 I will close this
