### ISSUE TITLE
Add option for FLUSHDB

### ISSUE THREAD

**Issue by Foxboron** [dial-once/node-cache-manager-redis#4]
Using this at work and currently need the ability to flush the connected DB. I see it's implemented in the redis library used by `sol-redis-pool` but i don't see anyway to try and hack around the store to access the option.

I'd love and appreciate if this option could be implemented.

**Comment by jkernech** [comment]
Thanks @Foxboron.

`flushdb()` may be a bit extreme if you end up storing something else in redis and unfortunately, `node-redis` does not support pattern deletion, e.g `del('sess:*')`

I will implement this feature in the near future and open an issue to suggest the addition of this feature to `node-cache-manager`

**Comment by Foxboron** [comment]
Thank you!
I'm aware it's a little bit extreme. But in my case, its what i need.

Love the quick response! Keep up the work.
