### ISSUE TITLE
cache-manager 1.2 breaking update?

### ISSUE THREAD

**Issue by amit777** [dial-once/node-cache-manager-redis#6]
Hi, I posted this issue in the main cache-manager project, but it's not clear to me yet whether it's a problem there or here:

https://github.com/BryanDonovan/node-cache-manager/issues/34

thanks!

**Comment by jkernech** [comment]
Thanks @amit777. I'll check this out soon.

**Comment by jkernech** [comment]
The problem was related to the multiCaching in `node-cache-manager`. The `isCacheableValue` function of the underlying cache was never called.

This PR should fix the issue https://github.com/BryanDonovan/node-cache-manager/pull/35

**Comment by BryanDonovan** [comment]
1.2.1 should fix this so you don't have to set the `isCacheableValue()` in the multiCaching initialization since it will now use the redis cache store's `isCacheableValue()`.

**Comment by jkernech** [comment]
Thanks @BryanDonovan !
