### ISSUE TITLE
Way to specify redis value types?

### ISSUE THREAD

**Issue by seanyesmunt** [dial-once/node-cache-manager-redis#63]
Is there a way to create a sorted set using node-cache-manager-redis? Every example I have seen just stores strings or a simple object.

I would like to be able to store a sorted set

**Comment by mrister** [comment]
Have you tried setting it ? If so can you please give  us a code example you used? We will be glad to update readme and add test cases  if it works, or you can even help and make a PR to add support if it does not. We should also consider Maps as well as Sets.

**Comment by seanyesmunt** [comment]
I actually just decided to go with [node_redis](https://github.com/NodeRedis/node_redis)
