### ISSUE TITLE
Support promises for set and get methods

### ISSUE THREAD

**Issue by lukechilds** [dial-once/node-cache-manager-redis#68]
The `set` and `get` methods on `node-cache-manager` support promises however those methods on `node-cache-manager-redis` don't. This means using this storage adapter breaks any code that uses promises on `set` and `get`.

e.g: 

Default memory store
```js
var cacheManager = require('cache-manager');
var cache = cacheManager.caching({ store: 'memory' });
cache.set('foo', 'bar')
  .then(() => cache.get('foo'))
  .then(console.log);
// "bar"
```
Redis store
```js
var cacheManager = require('cache-manager');
var redisStore = require('cache-manager-redis');
var cache = cacheManager.caching({ store: redisStore });
cache.set('foo', 'bar')
  .then(() => cache.get('foo'))
  .then(console.log);
// TypeError: Cannot read property 'then' of undefined
```

**Comment by mrister** [comment]
@lukechilds Yeah, we have had similar issues with people asking for promise support but it's not avail yet. Any chance you could help us out with a PR for that ?

**Comment by lukechilds** [comment]
Of course :)

**Comment by lukechilds** [comment]
Sorted, with tests 🎉

**Comment by lukechilds** [comment]
@mrister Sorted, with tests 🎉

**Comment by lukechilds** [comment]
@mrister Hey, sorry I know it's Christmas, just wondered if you had any idea when that PR would be merged and published. I'm waiting on it before publishing a module I've been working on.

**Comment by lukechilds** [comment]
Also, hope you had a good Christmas :)

**Comment by mrister** [comment]
@lukechilds new version is out!
