### ISSUE TITLE
How set max_attempts of connection?

### ISSUE THREAD

**Issue by Shadowman4205** [dial-once/node-cache-manager-redis#73]
How set max attempts like in redis_node?

**Comment by mrister** [comment]
@Shadowman4205 you should be able to pass params like those in redis_node

**Comment by mrister** [comment]
if you take a look at the code you shall se that we use https://github.com/joshuah/sol-redis-pool
and this it's options (redis) like in here https://github.com/dial-once/node-cache-manager-redis/blob/develop/index.js#L52

**Comment by Shadowman4205** [comment]
Thansks i used Retry Strategy.
