### ISSUE TITLE
How is multicache working?

### ISSUE THREAD

**Issue by Shadowman4205** [dial-once/node-cache-manager-redis#75]
Hi, i want implement this flow:

if redis store is not accessible then use memory cache instead. So i can get data or from db or from cache if redis is down fo some reason. Is multicache working like this?

**Comment by mrister** [comment]
@Shadowman4205 Yeah, let me give you a code sample that does this:

**Comment by mrister** [comment]
```js
const cacheManager = require('cache-manager');
const redisStore = require('cache-manager-redis');

const getRedisCache = (db, ttlRedis, host, port, pass, compress) =>
  cacheManager.caching({
    db,
    compress,
    store: redisStore,
    ttl: ttlRedis,
    host: host || 'localhost',
    port: port || 6379,
    auth_pass: pass,
  });

const getMemoryCache = (maxMemory, ttlMem) =>
  cacheManager.caching({
    max: maxMemory,
    ttl: ttlMem,
    store: 'memory',
  });

const buildCache = (options) => {
  const ttlMem = options.memory.ttl ||  10;

// default redis DB is 0
  const db = options.db || 0;

  const redisCache = getRedisCache(
    db,
    options.redis.ttl,
    options.redis.host,
    options.redis.port,
    options.redis.pass,
    options.redis.compress
  );
  const memoryCache = getMemoryCache(options.memory.max, ttlMem);

  return cacheManager.multiCaching([memoryCache, redisCache]);
};

```

**Comment by Shadowman4205** [comment]
Thank you very much, 
Here you returrning cacheManager.multiCaching([memoryCache, redisCache]), is this same with
cacheManager.multiCaching([redisCache, memoryCache]); or in first usage it will use memory cache first and after (if unsucceeded) it will use redis?
Also does this reduce the speed-perfomance?

**Comment by mrister** [comment]
I'm not sure about the performance (aside from overhead of switching to another memory store), but yeah order given in the array is important and thus goes the caches, in the example first memory then Redis.

**Comment by Shadowman4205** [comment]
One more question and i close issue(question).
The switching become if only one memory store unavailable?

**Comment by mrister** [comment]
I believe it works (this is cahce-manager-feature) like this:
1. Check for a key in memory cache if found return,  if not continue
2. Check key in redis cache and if found return, put to memory cache

**Comment by Shadowman4205** [comment]
On 

> Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379

it does not use memory cache

**Comment by mrister** [comment]
I think it does but both need to be set up properly, I guess you tested with some Invalid redis settings (url).

**Comment by Shadowman4205** [comment]
Yeah i tried on purpose with invalid url to test if the connection to redis fail, will it go to memory cache?

**Comment by Shadowman4205** [comment]
Ohhh then i have implement this functionality. Thank you.

**Comment by mrister** [comment]
@Shadowman4205 If you have some time please consider doing it as a Pull request to this repo. We would appreciate any additions.
