### ISSUE TITLE
Inconsistent use of promises

### ISSUE THREAD

**Issue by jscheffner** [dial-once/node-cache-manager-redis#79]
Is there a reason why `get` and `set` return promises but `del`and `keys` do not?

**Comment by mrister** [comment]
@jscheffner  I would say there isn't a reason but mostly how the module was used and developed over time (get and set were mostly used). They should be updated to support promises and if you have some time to contribute to a PR that would be most appreciated. 

Thanks for pointing out this one.

**Comment by jscheffner** [comment]
@mrister thanks for the quick response. I'll see if I can find the time to contribute.
