### ISSUE TITLE
Cache kills application after a few requests

### ISSUE THREAD

**Issue by kontextbewusst** [dial-once/node-cache-manager-redis#9]
Hi there,

I am using the redis cache (most recent versions of this module and the node-cache-manager) in a hapi-based server application and I am seeing a very strange problem. After a couple hundred requests to the cache, the server instances become unresponsive and all client requests time out. This does not occur when I switch to the mongodb cache.

I checked the redis log and my server's log and can't find anything that looks out of the order. Could you give me a hint or some suggestions on how I could trace this down further, or even fix the issue?

Thank you, Max.

**Comment by jkernech** [comment]
Thanks @kontextbewusst. I think the issue is related to #5. I'll check this out soon

**Comment by kontextbewusst** [comment]
@jkernech thank you! Let me know if I can help you with testing/debugging. I can easily reproduce the error in my environment.

**Comment by jkernech** [comment]
This PR https://github.com/dial-once/node-cache-manager-redis/pull/10 should fix your issue. I will publish a new version on npm today.

**Comment by jkernech** [comment]
@kontextbewusst I think I have successfully reproduce your issue. I think you use the reset method and the redis connection was not release in this case... The following PR #13 should fix the issue

**Comment by jkernech** [comment]
The v0.2.0 is available on npm : https://www.npmjs.com/package/cache-manager-redis
Could you check if this release solves your issue ?
Thanks

**Comment by jkernech** [comment]
@kontextbewusst Have you had time to test the new version?

**Comment by kontextbewusst** [comment]
@jkernech I just did and it works fine! Thank you very much for the fix!

**Comment by jkernech** [comment]
@kontextbewusst Thanks for your feedback. I'm glad to know that your issue is solved :)
